; Lo minimo para probar micro-ROS por serial.
;
;   pio run -t upload
;   ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyACM1 -b 115200
;   ros2 topic echo /min_counter

[env:esp32-s3-devkitc-1]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM8
lib_extra_dirs = ../lib
build_flags =
    -L../lib/micro_ros_kalman/src
    -lmicroros
