; Prueba de los dos puertos serie USB del ESP32-S3. Sin micro-ROS.
;
;   pio run -t upload            (carga por COM8, el conector UART)
;   pio device monitor -p COM8   (conector UART)
;   pio device monitor -p COM9   (conector USB nativo)

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
