; Prueba: micro-ROS sobre el USB nativo del S3 (COM9), logs por el UART (COM8).
; Reparto invertido respecto a test_serial/.
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
lib_extra_dirs = ../lib
build_flags =
    -L../lib/micro_ros_kalman/src
    -lmicroros
